# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d6969669ffa72263ad77dba8034c0fa228067fa07178b8d69e1a159015271448b349e4545aed044bc75840b3cd19c2460a694704800ac89947f773ce7428014

test:
  secret_key_base: 99b8b7f347e0845766b73fb12f10a640421de03730a5c37150ce0e7e9442efded003f7a05eeba8b04bff1e74027fe9596bd40c0dd92e5d193709043104e52686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
